### PR TITLE
Footer issue / Issue number #37

### PR DESCRIPTION
**Pull request by ZeeshanKhw**
I have made amendments to the footer by adding the footer tag and html content to the "index.hbs" file under the "templates" folder. 

I have added the css styling to the commons.scss under the scss folder for the footer.

I was unable to locate the MIT licence to add it to the repository.

### CODE REVIEW

**Comment by trullock** [comment]
Can we break this PR apart so the SASS and footer changes are separate please? I'll close this, then you can re-open two different PRs.

Use git branches to achieve this :)

**Comment by ZeeshanKhw** [comment]
Hi Andrew

Sure I’ll get that done.

Zeeshan

Sent from my iPhone

On 17 Sep 2019, at 19:33, Andrew Bullock <notifications@github.com<mailto:notifications@github.com>> wrote:


Can we break this PR apart so the SASS and footer changes are separate please? I'll close this, then you can re-open two different PRs.

Use git branches to achieve this :)

**Comment by ZeeshanKhw** [comment]
Dear Andrew

I have resubmitted the GitHub pull request and sent it over, but I have not had a response for a number of weeks.

Is the Web Development work experience still ongoing at the moment?

Regards


Zeeshan


________________________________

**Comment by trullock** [comment]
The issue is chap that each of your PRs have multiple changes in them which are nothing to do with the PR. 

Have a read up on git branching, you need to make each PR separately from `master`, instead you've done the first, then the 2nd, then the 3rd all on top of each other, so the 3rd contains 2 and 1.

**Comment by ZeeshanKhw** [comment]
Hi Andrew

I’ll have a look at that and try and make some changes to so that the commits are to individual branches.

Thank you.


Zeeshan

Sent from my iPhone

On 5 Nov 2019, at 09:08, Andrew Bullock <notifications@github.com> wrote:

﻿

The issue is chap that each of your PRs have multiple changes in them which are nothing to do with the PR.

Have a read up on git branching, you need to make each PR separately from master, instead you've done the first, then the 2nd, then the 3rd all on top of each other, so the 3rd contains 2 and 1.

**Pull request closed without merging**
